#!/usr/bin/env python3
"""Build the browsable catalog/ pages from the labeled tables in data/.

Everything under catalog/ is generated. Edit the CSVs or this script, then run:

    python3 scripts/build_catalog.py

The catalog never invents a number. It reads data/unified_labeled.csv,
data/questions.csv and the rollups, and it carries the same limits the report
carries: a company name is a tag unless a candidate said it, and a count is a
count of questions written down, never a probability that a room asks one.
"""

import csv
import os
import re
import sys
from collections import Counter, defaultdict

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATA = os.path.join(ROOT, "data")
OUT = os.path.join(ROOT, "catalog")
REPO = "breatheco-de/ai-engineer-interview-questions"

PRIORITY_NAMES = {
    "system_design": "System design",
    "evals": "Evals",
    "serving_cost": "Serving and cost",
    "fine_tuning": "Fine-tuning",
    "agent_reliability": "Agent reliability",
    "classic_ml": "Classic ML",
    "coding": "Coding",
    "tokens_attention": "Tokens and attention",
    "injection_gates": "Injection and gates",
    "project_defense": "Project defense",
    "context_sampling": "Context and sampling",
    "grounding": "Grounding",
    "api_control": "API and limits",
    "hybrid_search": "Hybrid search",
    "data_plane": "Data plane",
    "embeddings": "Embeddings",
    "chunking": "Chunking",
    "ann_indexes": "ANN indexes",
}

TASK_NAMES = {
    "explain": "explain",
    "design": "design",
    "implement": "implement",
    "diagnose": "diagnose",
    "defend": "defend",
    "evaluate": "evaluate",
}

SOURCE_BLURB = {
    "candidate": "A person described this interview, or an interviewer said they asked it.",
    "compiled report": "A compiled list marks it reported and cites a source we did not open.",
    "study bank": "A coach or a bank author wrote it as a topic to study.",
}

GENERATED = (
    "<!-- Generated by scripts/build_catalog.py. Do not edit by hand. -->\n"
)


def read(path):
    with open(os.path.join(DATA, path), encoding="utf-8") as fh:
        return list(csv.DictReader(fh))


def cell(text, limit=None):
    """Make a string safe inside a markdown table cell."""
    text = re.sub(r"\s+", " ", (text or "").strip())
    text = text.replace("|", "\\|")
    if limit and len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def pipe_list(value, limit=None):
    parts = [p for p in (value or "").split("|") if p]
    if limit and len(parts) > limit:
        shown = ", ".join(parts[:limit])
        return f"{shown} +{len(parts) - limit} more"
    return ", ".join(parts)


def search_link(term):
    query = f'repo:{REPO} "{term}"'.replace(" ", "+").replace(":", "%3A").replace('"', "%22")
    return f"https://github.com/search?q={query}&type=code"


def question_table(rows, show_sources=True):
    head = "| ID | Question | Task | Named in the text | Company tags |"
    rule = "|---|---|---|---|---|"
    if show_sources:
        head = head + " Sources |"
        rule = rule + "---|"
    out = [head, rule]
    for r in rows:
        named = ", ".join(x for x in [pipe_list(r["named_concepts"]), pipe_list(r["named_tools"])] if x)
        tags = pipe_list(r["companies_bank_tag"], limit=3)
        stated = pipe_list(r["companies_stated"])
        if stated:
            tags = f"**{stated}** (stated)" + (f"; {tags}" if tags else "")
        task = r["task_verb"] if r["task_use"] == "firm" else f"_{r['task_verb']}_ (review)"
        line = (
            f"| `{r['unified_id']}` | {cell(r['question_text'], 220)} | {task} | "
            f"{cell(named, 60) or '—'} | {cell(tags, 70) or '—'} |"
        )
        if show_sources:
            line = line + f" {cell(pipe_list(r['source_authors']), 60)} |"
        out.append(line)
    return "\n".join(out)


def write(path, text):
    full = os.path.join(OUT, path)
    os.makedirs(os.path.dirname(full), exist_ok=True)
    with open(full, "w", encoding="utf-8") as fh:
        fh.write(text if text.endswith("\n") else text + "\n")
    return full


def build_priority_pages(rows):
    by_priority = defaultdict(list)
    for r in rows:
        by_priority[r["primary_priority"]].append(r)

    summary = []
    for slug, name in PRIORITY_NAMES.items():
        group = by_priority.get(slug, [])
        firm = [r for r in group if r["primary_use"] == "firm"]
        review = [r for r in group if r["primary_use"] != "firm"]
        cand = [r for r in firm if int(r["n_candidate"]) > 0]
        comp = [r for r in firm if int(r["n_compiled_report"]) > 0]
        bank = [r for r in firm if int(r["n_study_bank"]) > 0]
        summary.append(
            dict(slug=slug, name=name, firm=len(firm), review=len(review),
                 cand=len(cand), comp=len(comp), bank=len(bank))
        )

        tasks = Counter(r["task_verb"] for r in firm if r["task_use"] == "firm")
        task_line = ", ".join(f"{TASK_NAMES.get(t, t)} {n}" for t, n in tasks.most_common())

        page = [
            GENERATED,
            f"# {name}",
            "",
            f"{len(firm)} questions carry a firm `{slug}` label: "
            f"{len(cand)} appear in a candidate sitting, {len(comp)} in a compiled report, "
            f"{len(bank)} in a study bank. A question counted in two sources is counted in each.",
            "",
            f"What the candidate is asked to do: {task_line or '—'}.",
            "",
            "These are counts of questions that were written down. They are not the probability "
            "that anyone asks them. Company names are tags copied from a bank unless the cell says "
            "*stated*, which means the candidate named the employer.",
            "",
            "[← back to the catalog](../README.md) · "
            "[the report](../../REPORT.md) · "
            f"[the labeled rows](../../data/unified_labeled.csv)",
            "",
        ]

        for label, key, group_rows in (
            ("Asked in a sitting", "candidate", cand),
            ("In a compiled report", "compiled report", comp),
            ("In a study bank", "study bank", bank),
        ):
            page += [f"## {label} — {len(group_rows)}", "", SOURCE_BLURB[key], ""]
            if group_rows:
                if len(group_rows) > 40:
                    page += ["<details>", f"<summary>Show all {len(group_rows)} questions</summary>", ""]
                    page += [question_table(group_rows), "", "</details>", ""]
                else:
                    page += [question_table(group_rows), ""]
            else:
                page += ["None in this corpus.", ""]

        if review:
            page += [
                f"## Labeled `{slug}`, but not firmly — {len(review)}",
                "",
                "The classifier returned this priority below 0.6 confidence, or returned `unclear`. "
                "These rows stay in the data and stay out of every count above.",
                "",
                "<details>",
                f"<summary>Show {len(review)} review rows</summary>",
                "",
                question_table(review),
                "",
                "</details>",
                "",
            ]

        write(f"priorities/{slug.replace('_', '-')}.md", "\n".join(page))

    return summary


def build_sittings(rows, instances):
    by_id = {r["instance_id"]: r for r in instances}
    cand = [r for r in rows if int(r["n_candidate"]) > 0]

    sittings = defaultdict(list)
    for r in cand:
        first = None
        for iid in r["instance_ids"].split("|"):
            inst = by_id.get(iid)
            if inst and inst["evidence_tier"] == "1_first_hand":
                first = inst
                break
        key = (first["source_author"] if first else "unknown",
               first["source_url"] if first else "",
               first["source_date"] if first else "",
               first["company"] if first else "",
               first["level_guess"] if first else "")
        sittings[key].append((r, first))

    page = [
        GENERATED,
        "# The sittings",
        "",
        f"{len(cand)} questions in this corpus have at least one first-hand instance: someone who sat "
        "the interview wrote the question down, or an interviewer said they asked it. Everything else "
        "in the register is a compiled report or a study bank.",
        "",
        "This is the smallest slice and the only one that describes a room. Forty-five questions are "
        "not a sample of the industry, and several come from the same post. Read them as testimony, "
        "not as a distribution.",
        "",
        "[← back to the catalog](README.md) · "
        "[how each sitting was coded](../docs/ingestion.md) · "
        "[the report](../REPORT.md)",
        "",
    ]

    order = sorted(sittings.items(), key=lambda kv: -len(kv[1]))
    for (author, url, date, company, level), pairs in order:
        title = f"## {author}"
        page += [title, ""]
        meta = []
        if date:
            meta.append(date)
        if company:
            meta.append(f"employer named by the candidate: **{company}**")
        if level and level not in ("unknown", "none"):
            meta.append(f"level read from the post: {level}")
        if url:
            meta.append(f"[source]({url})")
        page += [" · ".join(meta) if meta else "_source line not recorded_", ""]
        page += ["| ID | Question | Priority | Task |", "|---|---|---|---|"]
        for r, _inst in sorted(pairs, key=lambda p: p[0]["unified_id"]):
            pr = PRIORITY_NAMES.get(r["primary_priority"], r["primary_priority"])
            if r["primary_use"] != "firm":
                pr = f"_{pr}_ (review)"
            tk = r["task_verb"] if r["task_use"] == "firm" else f"_{r['task_verb']}_ (review)"
            page.append(f"| `{r['unified_id']}` | {cell(r['question_text'], 260)} | {pr} | {tk} |")
        page.append("")

    page += [
        "## Level",
        "",
        "| Level read from the post | First-hand instances |",
        "|---|---|",
    ]
    for r in read("rollups/sitting_level.csv"):
        page.append(f"| {r['level_guess']} | {r['n_first_hand_instances']} |")
    page += [
        "",
        "Senior and mid are our reading of the post, not a level the employer printed. Both study "
        "banks leave level blank on every row, so this corpus cannot support a junior/mid/senior "
        "chart of the whole register.",
        "",
    ]
    write("sittings.md", "\n".join(page))
    return len(cand)


def build_companies(rows):
    prio = read("rollups/rollup_company_priority.csv")
    tops = read("rollups/rollup_company_questions.csv")

    tagged, firm = defaultdict(int), defaultdict(int)
    by_company_priority = defaultdict(list)
    for r in prio:
        tagged[r["company"]] += int(r["n_tagged_questions"])
        firm[r["company"]] += int(r["n_firm"])
        by_company_priority[r["company"]].append(r)

    stated = defaultdict(list)
    for r in rows:
        for name in (r["companies_stated"] or "").split("|"):
            if name:
                stated[name].append(r)

    page = [
        GENERATED,
        "# Company tags",
        "",
        "**These are tags, not interviews.** In the lab notebook, 1,309 of 1,326 company rows are a "
        "name a bank author attached to a question. Seventeen were stated by the person who sat the "
        "interview. A tag pile says what a coach filed under a company's name. It does not say that "
        "the company asked the question, and no count here is a probability.",
        "",
        "[← back to the catalog](README.md) · "
        "[the tag figure](../figures/company-tags.png) · "
        "[the full rollup](../data/rollups/rollup_company_priority.csv)",
        "",
        "## Employers a candidate actually named",
        "",
        "| Employer | Questions | Who said it |",
        "|---|---|---|",
    ]
    for name, rs in sorted(stated.items(), key=lambda kv: -len(kv[1])):
        authors = sorted({a for r in rs for a in r["source_authors"].split("|") if a})
        page.append(f"| **{name}** | {len(rs)} | {', '.join(authors)} |")
    page += [
        "",
        "Every other name on this page came off a bank.",
        "",
        "## What the banks file under each name",
        "",
        "| Tag | Tagged questions | Firmly labeled | Largest firm priorities |",
        "|---|---|---|---|",
    ]
    for name in sorted(tagged, key=lambda c: -tagged[c]):
        top = sorted(by_company_priority[name], key=lambda r: -int(r["n_firm"]))[:3]
        detail = ", ".join(
            f"{PRIORITY_NAMES.get(r['priority'], r['priority'])} {r['n_firm']}" for r in top if int(r["n_firm"])
        )
        anchor = re.sub(r"[^a-z0-9]+", "-", name.lower()).strip("-")
        page.append(f"| [{name}](#{anchor}) | {tagged[name]} | {firm[name]} | {detail or '—'} |")
    page += ["", "## The top ten questions in each tag pile", ""]

    for name in sorted(tagged, key=lambda c: -tagged[c]):
        page += [f"### {name}", "",
                 f"{tagged[name]} questions carry this tag. A tag is what a bank author wrote next to "
                 f"the question, not a room we attended.", "",
                 "| # | Question | Priority | Sources |", "|---|---|---|---|"]
        for r in [t for t in tops if t["company"] == name]:
            pr = PRIORITY_NAMES.get(r["primary_priority"], r["primary_priority"])
            if r["primary_use"] != "firm":
                pr = f"_{pr}_ (review)"
            page.append(
                f"| {r['rank']} | {cell(r['question_text'], 200)} | {pr} | {cell(r['source_types'])} |"
            )
        page.append("")

    write("companies.md", "\n".join(page))
    return len(tagged), len(stated)


def build_named_terms():
    page = [
        GENERATED,
        "# Named concepts and tools",
        "",
        "A term is counted when the question text says it. A question that asks about a vector index "
        "without writing HNSW is not in the HNSW row. A mention in an interview question is not a job "
        "requirement, and these are not firm classifier labels — they are string matches against a "
        "closed list fixed in [Phase 1](../docs/PHASE1.md).",
        "",
        "[← back to the catalog](README.md) · "
        "[concepts figure](../figures/concepts.png) · "
        "[tools figure](../figures/tools.png)",
        "",
    ]
    for title, path, note in (
        ("Concepts", "rollups/rollup_concepts.csv",
         "What the corpus names when it names an idea."),
        ("Tools", "rollups/rollup_tools.csv",
         "Named products and libraries. MCP is the only one this corpus names often."),
    ):
        page += [f"## {title}", "", note, "",
                 "| Term | Questions | Candidate | Compiled report | Study bank | Find it |",
                 "|---|---|---|---|---|---|"]
        for r in read(path):
            page.append(
                f"| {r['name']} | {r['n_questions']} | {r['n_candidate']} | "
                f"{r['n_compiled_report']} | {r['n_study_bank']} | "
                f"[search]({search_link(r['name'])}) |"
            )
        page.append("")
    write("named-terms.md", "\n".join(page))


def build_index(summary, n_cand, n_companies, n_stated, rows):
    tasks = Counter(r["task_verb"] for r in rows if r["task_use"] == "firm")
    task_cand = Counter(
        r["task_verb"] for r in rows if r["task_use"] == "firm" and int(r["n_candidate"]) > 0
    )
    page = [
        GENERATED,
        "# Browse the questions",
        "",
        f"1,988 questions, one row each, sorted into eighteen priorities. Each page below lists the "
        "questions under one priority, split by where the question came from: a candidate who sat the "
        "interview, a compiled report, or a study bank. That split is the point. The three sources "
        "disagree, and a page that merged them would hide it.",
        "",
        "**A count here is a count of questions that were written down.** It is not the chance a room "
        "asks one. Read [the report](../REPORT.md) before you read a number off this page.",
        "",
        "| Where to start | |",
        "|---|---|",
        f"| [The sittings](sittings.md) | The {n_cand} questions someone actually reported from a room. Start here. |",
        "| [Company tags](companies.md) | What coaches file under a company's name. Tags, not interviews. |",
        "| [Named concepts and tools](named-terms.md) | Which words the questions actually use. |",
        "| [Figures](../figures/) | The seven pictures behind the findings. |",
        "| [The raw tables](../data/README.md) | Every row, the column meanings, and how to load them. |",
        "",
        "## The eighteen priorities",
        "",
        "| Priority | Firm questions | In a sitting | In a compiled report | In a study bank |",
        "|---|---|---|---|---|",
    ]
    for s in sorted(summary, key=lambda s: -s["firm"]):
        page.append(
            f"| [{s['name']}](priorities/{s['slug'].replace('_', '-')}.md) | {s['firm']} | "
            f"{s['cand']} | {s['comp']} | {s['bank']} |"
        )
    page += [
        "",
        "A question that appears in two source types is counted under each of them, so the last three "
        "columns can add to more than the first. 469 further questions were labeled below the "
        "confidence bar; each priority page lists its own review rows in a collapsed block.",
        "",
        "## What the question asks you to do",
        "",
        "| Task | Firm questions | Of which from a sitting |",
        "|---|---|---|",
    ]
    for task, n in tasks.most_common():
        page.append(f"| {TASK_NAMES.get(task, task)} | {n} | {task_cand.get(task, 0)} |")
    page += [
        "",
        "`explain` means define or compare. It was added to the list before labeling, because "
        "\"what is a KV cache?\" is not a design question and forcing it into `design` would have "
        "inflated design.",
        "",
        "---",
        "",
        "Every page under `catalog/` is generated by "
        "[`scripts/build_catalog.py`](../scripts/build_catalog.py) from the tables in "
        "[`data/`](../data/). Fix the data, re-run the script; do not edit these pages by hand.",
        "",
    ]
    write("README.md", "\n".join(page))


def main():
    rows = read("unified_labeled.csv")
    instances = read("questions.csv")
    summary = build_priority_pages(rows)
    n_cand = build_sittings(rows, instances)
    n_companies, n_stated = build_companies(rows)
    build_named_terms()
    build_index(summary, n_cand, n_companies, n_stated, rows)
    print(f"catalog built: {len(PRIORITY_NAMES)} priority pages, "
          f"{n_cand} candidate questions, {n_companies} company tags")
    return 0


if __name__ == "__main__":
    sys.exit(main())
